### ISSUE TITLE
Небольшое ускорение

### ISSUE THREAD

**Issue by AshFungor** [randommfs/HPool#2]
В целом ща это выглядит прикольно, но хочеца:
- избавиться от O(n) для нового блока, можно как вот тут по сути вместо used +find_next_free_block() представить pool как граф и потом вынимать или встраивать новые блоки по необходимости https://github.com/mtrebi/memory-allocators
едиственный problem - указатель обычно 2 байта занимает, а bool - 1, поэтому чуть жирней пул получиться
- может совместимость со смарт поинтерами из std сделать?
как вариант можно сделать hpool_unique_ptr, hpool_shared_ptr, hpool_weak_ptr, унаследовать их и сделать кастомных конструктор для hpool

**Comment by HyperWinX** [comment]
Первое выполнено. Интересно кем🤣

**Comment by AshFungor** [comment]
готово в #4 #3
